services:
  db:
    image: mysql:8.0
    container_name: todo_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    volumes:
      - 'db_data:/var/lib/mysql'
      - './migrations/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: todo_nginx
    ports:
      - "8080:80"
    volumes:
      - './public:/var/www/html/public'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - db
    working_dir: '/var/www/html/public'

  php:
    build: .
    container_name: todo_php
    volumes:
      - './public:/var/www/html/public'
      - './config:/var/www/html/config'
      - './src:/var/www/html/src'
    working_dir: '/var/www/html'

volumes:
  db_data:
